// <auto-generated />
using System;
using FinanceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApi.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20251003162303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("FinanceApi.Model.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DividendYield")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            DividendYield = 0.6m,
                            LastUpdated = new DateTime(2025, 10, 3, 16, 23, 3, 24, DateTimeKind.Utc).AddTicks(4062),
                            Price = 170.50m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft Corp.",
                            DividendYield = 0.8m,
                            LastUpdated = new DateTime(2025, 10, 3, 16, 23, 3, 24, DateTimeKind.Utc).AddTicks(4065),
                            Price = 320.75m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Tesla Inc.",
                            DividendYield = 0.0m,
                            LastUpdated = new DateTime(2025, 10, 3, 16, 23, 3, 24, DateTimeKind.Utc).AddTicks(4067),
                            Price = 250.10m,
                            Symbol = "TSLA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
